### ISSUE TITLE
Email invoice link

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#3]
Clicking link in invoice when not logged in takes you to a "your cart is empty" page, this should be able to be paid via the link even if not logged in.

**Comment by kprajapatii** [comment]
Fixed

**Comment by Stiofan** [comment]
This is not fixed, if i redend the invoice an invoice is sent to the customer with no pay link, there is a link tot he invoice such as https://www.site.com/wpi_invoice/wpinv-8767/ which will also lead to 404 if not logged in, not good enough.
